[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_filters = 
    time
    colorize
    default

; Порт подключения (будет автоматически определяться)
; upload_port = /dev/cu.usbserial-1430

; Скорость загрузки
board_upload.speed = 460800

; OTA настройки (тестирование пока отложено)
; upload_protocol = espota
; upload_port = 192.168.1.184
; upload_flags =
;     --auth=st01ota2026
;     --timeout=120

; Библиотеки
lib_deps = 
    paulstoffregen/OneWire@^2.3.8
    DallasTemperature@^3.11.0
    bblanchon/ArduinoJson@^7.2.0
    knolleary/PubSubClient@^2.8
